# Generated by Django 2.1.1 on 2018-11-26 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=False)),
                ('absence', models.BooleanField(default=True)),
                ('late', models.BooleanField(default=False)),
                ('personal_leave', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='date_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=11)),
                ('course_name', models.CharField(default='course0', max_length=50)),
                ('memo', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isIntern', models.BooleanField(default=False)),
                ('isJunior', models.BooleanField(default=False)),
                ('isSenior', models.BooleanField(default=False)),
                ('isFamily', models.BooleanField(default=True)),
                ('isMentor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atdSummary', to='attendanceSheet.date_course'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendanceSheet', to=settings.AUTH_USER_MODEL),
        ),
    ]
