# Generated by Django 2.1.1 on 2018-12-20 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendanceSheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('applicateDate', models.CharField(default='', max_length=11)),
                ('under_review', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atdSummary_leave', to='attendanceSheet.date_course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaveApplications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
